
services:
  server:
    image: youthing/sse-spring:1.0.2
    container_name: sse-example
    ports:
      - "8082:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis1

  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6380:6379"
    volumes:
      - redis1_data:/data

volumes:
  redis1_data:
